### ISSUE TITLE
I can not run PluginManager and Webp

### ISSUE THREAD

**Issue by Hotte512** [shyim/ShyimPluginManager#4]
I get following Error after installation of PluginManager, webp or PluginManager are working alone but not together. Also having both installed and only webp enabled brings this error.
Do you have any idea if I do anything wrong?

Fatal error: Uncaught Error: Call to undefined method ShyimWebP\Commands\GenerateWebpImages::getDefaultName() in /var/www/vhosts/DOMAIN.de/httpdocs/_dev2/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php:61 Stack trace: #0 /var/www/vhosts/DOMAIN.de/httpdocs/_dev2/vendor/symfony/dependency-injection/Compiler/Compiler.php(141): Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #1 /var/www/vhosts/DOMAIN.de/httpdocs/_dev2/vendor/symfony/dependency-injection/ContainerBuilder.php(788): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #2 /var/www/vhosts/DOMAIN.de/httpdocs/_dev2/engine/Shopware/Kernel.php(563): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #3 /var/www/vhosts/DOMAIN.de/httpdocs/_dev2/engine/Shopware/Kernel.php(304): Shopware\Kernel->initializeContainer() #4 /var/www/vhosts/ in /var/www/vhosts/DOMAIN.de/httpdocs/_dev2/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php on line 61

**Comment by shyim** [comment]
That looks like a mix up with symfony/console dependency
